### PR TITLE
Schema fixes

### PR DESCRIPTION
**Pull request by grncdr**
Great work! I just needed to add these two small fixes to parse the schema for my app.

### CODE REVIEW

**Comment by alisnic** [comment]
Great patch? can you also update https://github.com/alisnic/solargraph-arc/blob/master/spec/solargraph-arc/schema_spec.rb#L6 to cover this case?

**Comment by grncdr** [comment]
Done ✅

**Comment by alisnic** [comment]
Great! can you also run the tests locally using instructions in https://github.com/alisnic/solargraph-arc#contributing? It seems that schema_spec.rb assertions need to be updated

**Comment by grncdr** [comment]
I was a bit busy yesterday and meant to finish writing #25 before I responded here. Thanks again!

**Pull request merged**
